version: "3"

services:
  mongo:
    container_name: ssdl-mongo
    image: mongo:latest
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - mongodb_volume:/data/db

  ssdl:
    container_name: ssdl
    command: "python -m ssdl"
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - TELEGRAM_BOT_API_KEY=$TELEGRAM_BOT_API_KEY
      - SSDL_ADMIN=$SSDL_ADMIN
    depends_on:
      - ssdl-mongo

  mongo_express:
    container_name: ssdl-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    expose:
      - ${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=ssdl-mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=SieSollenDeutschLernen
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - ssdl-mongo

volumes:
  mongodb_volume:
