version: "3"

services:
  ssdl-mongo:
    container_name: ssdl-mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_volume:/data/db
    expose:
      - ${MONGODB_PORT:-27017}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}

  ssdl:
    container_name: ssdl
    command: "python -m ssdl"
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - TELEGRAM_BOT_API_KEY=$TELEGRAM_BOT_API_KEY
      - SSDL_ADMIN=$SSDL_ADMIN
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-username}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
    depends_on:
      - ssdl-mongo

  mongo_express:
    container_name: ssdl-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=ssdl-mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD:-password}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - ssdl-mongo

volumes:
  mongodb_volume:
